export default function Programacion101_2() {
    return (
        <div>
            <h1>Página en proceso 2</h1>
            <blockquote cite="https://es.wikipedia.org/wiki/Lorem_ipsum">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
                Lorem ipsum dolor sit amet, consectetur adipiscing elit...
            </blockquote>
        </div>
    )
}